// <auto-generated />
using System;
using System.Resources;
using System.Globalization;

namespace InterfaceTrafficWatch.Properties
{
    internal static class Resources
    {
        private static ResourceManager resourceMan;
        private static CultureInfo resourceCulture;

        internal static ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    // resource files are embedded with the project's root namespace (NetSpeed)
                    resourceMan = new ResourceManager("NetSpeed.Properties.Resources", typeof(Resources).Assembly);
                }
                return resourceMan;
            }
        }

        internal static CultureInfo Culture
        {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        // Image resources
        internal static System.Drawing.Bitmap metal1 { get { object obj = ResourceManager.GetObject("metal1", resourceCulture); return ((System.Drawing.Bitmap)(obj)); } }
        internal static System.Drawing.Bitmap IMG_4058_rawlr { get { object obj = ResourceManager.GetObject("IMG_4058_rawlr", resourceCulture); return ((System.Drawing.Bitmap)(obj)); } }

        // String resources used in UI
        internal static string Setup_Label_Interface => ResourceManager.GetString("Setup_Label_Interface", resourceCulture);
        internal static string Setup_MaxDL => ResourceManager.GetString("Setup_MaxDL", resourceCulture);
        internal static string Setup_MaxUP => ResourceManager.GetString("Setup_MaxUP", resourceCulture);
        internal static string Setup_Units_KBs => ResourceManager.GetString("Setup_Units_KBs", resourceCulture);
        internal static string Setup_Refresh => ResourceManager.GetString("Setup_Refresh", resourceCulture);
        internal static string Setup_ms => ResourceManager.GetString("Setup_ms", resourceCulture);
        internal static string Setup_OK => ResourceManager.GetString("Setup_OK", resourceCulture);
        internal static string Setup_Cancel => ResourceManager.GetString("Setup_Cancel", resourceCulture);
        internal static string Setup_Title => ResourceManager.GetString("Setup_Title", resourceCulture);
        internal static string Setup_Check_DisplayInBits => ResourceManager.GetString("Setup_Check_DisplayInBits", resourceCulture);
        internal static string Setup_Label_Language => ResourceManager.GetString("Setup_Label_Language", resourceCulture);

        internal static string Menu_Minimize => ResourceManager.GetString("Menu_Minimize", resourceCulture);
        internal static string Menu_Show => ResourceManager.GetString("Menu_Show", resourceCulture);
        internal static string Menu_AlwaysOnTop => ResourceManager.GetString("Menu_AlwaysOnTop", resourceCulture);
        internal static string Menu_Config => ResourceManager.GetString("Menu_Config", resourceCulture);
        internal static string Menu_About => ResourceManager.GetString("Menu_About", resourceCulture);
        internal static string Menu_Exit => ResourceManager.GetString("Menu_Exit", resourceCulture);

        internal static string Msg_InitError => ResourceManager.GetString("Msg_InitError", resourceCulture);
        internal static string Msg_SetupError => ResourceManager.GetString("Msg_SetupError", resourceCulture);
        internal static string Title_Error => ResourceManager.GetString("Title_Error", resourceCulture);

        internal static string MainForm_Title => ResourceManager.GetString("MainForm_Title", resourceCulture);
        internal static string MainForm_TrayFormat => ResourceManager.GetString("MainForm_TrayFormat", resourceCulture);
        internal static string MainForm_In => ResourceManager.GetString("MainForm_In", resourceCulture);
        internal static string MainForm_Out => ResourceManager.GetString("MainForm_Out", resourceCulture);

        internal static string Lang_English => ResourceManager.GetString("Lang_English", resourceCulture);
        internal static string Lang_Polish => ResourceManager.GetString("Lang_Polish", resourceCulture);
        internal static string Lang_Chinese => ResourceManager.GetString("Lang_Chinese", resourceCulture);
        internal static string Lang_Japanese => ResourceManager.GetString("Lang_Japanese", resourceCulture);
    }
}
